<?php
/**
 * @file
 * token insert module.
 */
function token_insert_text_element_info_alter(&$types) {
  if (user_access('use token insert')) {
    $types['text_format']['#post_render'][] = 'token_insert_text_post_render';
    $types['textarea']['#post_render'][] = 'token_insert_text_post_render';
  }
}


function token_insert_text_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'field_ui_field_edit_form' && user_access('administer token insert settings')) {
    
    $form['token_insert'] = array(
      '#title' => t('Token Insert'),
      '#type' => 'fieldset',
      '#collapsible' => FALSE,
    );

    $form['token_insert']['use_for_token_insert'] = array(
      '#type' => 'checkbox',
      '#title' => t('Use Token Insert for this field'),
      //variable_get('token_insert_content_type_*typename*_*fieldname*, 0)
      '#default_value' => variable_get('token_insert_content_type_' . $form['instance']['bundle']['#value'] . '_' . $form['instance']['field_name']['#value'], 0),
      '#description' => t('If selected Token Insert will be available for this field'),
    );

    $form['#submit'][] = 'token_insert_text_add_contenttype';

  }
}

function token_insert_text_add_contenttype($form, &$form_state) {
  variable_set('token_insert_content_type_' . $form['instance']['bundle']['#value'] . '_' . $form['instance']['field_name']['#value'],  $form_state['values']['use_for_token_insert']);
}

function token_insert_text_post_render($content, $element) {

  if (isset($element['#entity_type']) && isset($element['#bundle'])) {
    if ($element['#entity_type'] == 'node' && variable_get('token_insert_content_type_' . $element['#bundle'] . '_' . $element['#field_name'], 0) == 1) {
      module_load_include('inc', 'token_insert', 'token_insert');
      drupal_add_js(drupal_get_path('module', 'token_insert') . '/token_insert.js');
      drupal_add_js(drupal_get_path('module', 'token_insert_text') . '/token_insert_text.js');
      if (!isset($element['summary'])) {
        $contentarray = token_insert_text_combobox($element);
        $content .= drupal_render($contentarray);
      }
      if (isset($element['#name'])) {
       // $content .= drupal_get_form('token_insert_text_combobox', $element['#name']);
       $content .= drupal_render(drupal_get_form('token_insert_text_combobox', $element['#name']));
      }
    }
  }
  return $content;
}

function token_insert_text_combobox($element) {
  $form = array();
  if (isset($element['#title'])) {
    $options = token_insert_get_tokens();
    $name = strtolower($element['#title']);
    $settings['token_insert']['buttons']["token-insert-text-button-$name"] = $element['#id'];
    drupal_add_js($settings, array('type' => 'setting')) ;
    $form['token_insert_text_combobox'] = array(
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#title' => t('Insert token'),
    );
    $form['token_insert_text_combobox']['token_insert_text_select'] = array(
      '#type' => 'select',
      '#options' => $options,
      '#attributes' => array(
        'id' => array("token-insert-text-select-$name"),
      ),
    );

    $form['token_insert_text_combobox']['token_insert_text_button'] = array(
      '#type' => 'button',
      '#value' => t('Insert'),
      '#executes_submit_callback' => FALSE,
      '#attributes' => array(
        'class' => array('token-insert-text-button'),
        'rel' => $name,
        'id' => array("token-insert-text-button-$name"),
      ),
    );
  }
  return $form;

}
